version: "3.9"
services:
  app:
    container_name: "mediapp-backend-spring-boot2"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db_2:5432/mediappbd
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=bar2005XP
    depends_on:
      - postgres_db

  postgres_db:
    container_name: "postgres_db_2"
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "bar2005XP"
      POSTGRES_DB: "mediappbd"

volumes:
  postgres-data: